In [ ]:
#########################################################################
#########------- Machine Learning Inmersion ------------#################
#########################################################################
# Capacitador: André Omar Chávez Panduro
# email: andrecp38@gmail.com
# Introduccion Python - DesarrolloAlgoritmosMachineLearning
# version: 1.0
#########################################################################

![image.png](attachment:image.png)

In [12]:
from google.colab import drive
import os
drive.mount('/content/drive/')
os.chdir('/content/drive/My Drive/Académico/MLI/Sesion03 - ModelosSupervisados/DataSet')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [13]:
%matplotlib inline 
import numpy as np # Trabajar con arreglos ( Vectores y matrices)
import pandas as pd # Lectura de datos (Input/Output)
import matplotlib.pyplot as plt # Graficos en Python

np.random.seed(42)

En primer lugar vamos a probar con un ejemplo muy sencillo: ajustar una recta a unos datos. Esto difícilmente se puede llamar _machine learning_, pero nos servirá para ver cómo es la forma de trabajar con `scikit-learn`, cómo se entrenan los modelos y cómo se calculan las predicciones.

In [14]:
# Lectura de datos
data = pd.read_csv("Churn-arboles.csv")

In [15]:
# Ver los primeros
data.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO AUTO    CHURN
0   0    57   Femenino   Casado      2  27535.3   Si     Fuga
1   4    68   Femenino   Casado      2  81000.9   No     Fuga
2   8    34  Masculino  Soltero      0  87467.1   Si  No Fuga
3  10    60  Masculino   Casado      2  83220.6   No     Fuga
4  13    28   Femenino   Casado      2  20850.4   No     Fuga

In [16]:
# Cambiamos los datos string a numeros para que los algoritmos puedan trabajar
columnas_categoricas = ["SEXO","CIVIL","AUTO","CHURN"]

In [17]:
from sklearn.preprocessing import LabelEncoder
for c in columnas_categoricas:
    print(str(c))
    le = LabelEncoder()
    le.fit(data[str(c)])
    data[str(c)]=le.transform(data[str(c)]) 

SEXO
CIVIL
AUTO
CHURN


In [18]:
# Observar el encoding
data.head(10)

ID  EDAD  SEXO  CIVIL  HIJOS   INGRESO  AUTO  CHURN
0   0    57     0      0      2  27535.30     1      0
1   4    68     0      0      2  81000.90     0      0
2   8    34     1      1      0  87467.10     1      1
3  10    60     1      0      2  83220.60     0      0
4  13    28     0      0      2  20850.40     0      0
5  17    52     1      1      0  84112.60     0      1
6  19    87     0      1      2   3776.12     0      0
7  20    88     0      0      2  73865.90     1      0
8  22    76     1      0      2  30933.60     1      1
9  23    76     0      0      1  12309.60     0      0

In [ ]:
#data.dtypes

El proceso para usar `scikit-learn` es el siguiente:

1. Separar los datos en matriz de características `features` y variable a predecir `y`
2. Seleccionar el modelo
3. Elegir los hiperparámetros
4. Ajustar o entrenar el modelo (`model.fit`)
5. Predecir con datos nuevos (`model.predict`)

In [19]:
# Paso1: Llamamos un modelo analítco
# Llamamos a la libreria de modelos
from sklearn.linear_model import LogisticRegression

In [20]:
# Paso2: Definimos el modelo
Modelito = LogisticRegression() # Utiliza los parámetros por defecto

In [21]:
# Generamos el frame de drivers o features.
# X - y
drivers=["EDAD","SEXO","CIVIL","HIJOS","INGRESO","AUTO"]
X = data[drivers]

In [ ]:
X.head(3)

EDAD  SEXO  CIVIL  HIJOS  INGRESO  AUTO
0    57     0      0      2  27535.3     1
1    68     0      0      2  81000.9     0
2    34     1      1      0  87467.1     1

In [22]:
# Generamos el frame del target o variable objetivo
y=data["CHURN"]

In [23]:
# Paso 03:  Particion muestral
from sklearn.model_selection import train_test_split

In [24]:
# X_train, X_test, Y_train, Y_test =
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.30)

In [25]:
# Paso04: Ajusto un modelo predictivo
Modelito.fit(X_train, y_train) # Ajuste o entrenamiento

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [44]:
Modelito.coef_

array([[-2.03886051e-02,  1.98666960e+00,  1.55908123e-01,
         4.37022724e-01,  3.78885080e-06,  6.09133755e-02]])

In [45]:
Modelito.intercept_

array([0.20481668])

In [29]:
# Paso05: Predecimos con el algoritmo entrenado
y_hat = Modelito.predict(X_test)
y_hat[0:5]

array([1, 1, 1, 0, 1])

In [47]:
table=pd.crosstab(index=y_hat,columns=y_test, margins=True)
table

CHURN    0    1  All
row_0               
0       83   34  117
1       68  219  287
All    151  253  404

Para calcular el error, en el módulo `sklearn.metrics` tenemos varias funciones útiles:

In [30]:
# Paso06: Validamos el mdodelo predictivo
from sklearn import metrics

In [31]:
precision_global = metrics.accuracy_score(y_true=y_test, y_pred=y_hat)
precision_global

0.7475247524752475

Y ahora predecimos con datos nuevos:

In [57]:
# Paso6: Implementamos un modelo predictivo
data_new = pd.read_csv("Churn-arboles-nuevos.csv")

In [58]:
data_new.head(2)

ID  EDAD      SEXO   CIVIL  HIJOS  INGRESO AUTO
0   0    57  Femenino  Casado      2  27535.3   Si
1   4    68  Femenino  Casado      2  81000.9   No

In [59]:
# Le hacemos label encoding tambien
columnas_categoricas = ["SEXO","CIVIL","AUTO"]
for c in columnas_categoricas:
    print(str(c))
    le = LabelEncoder()
    le.fit(data_new[str(c)])
    data_new[str(c)]=le.transform(data_new[str(c)]) 

SEXO
CIVIL
AUTO


In [53]:
# data_new.head(1)

In [64]:
# Le retiramos el ID o identificador unico
data_new_2 = data_new
data_new_2 = data_new_2.drop("ID",axis=1)

In [65]:
# Paso07: Con el modelo entrenado, hago la prediccion para nuevos individuos
y_campanas = Modelito.predict(data_new_2)

In [66]:
y_campanas

array([1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0])

In [79]:
pd.DataFrame(np.hstack((data_new['ID'].values.reshape(-1,1),y_campanas.reshape(-1,1))),columns=['ID','y_pred']).head(4)

ID  y_pred
0   0       1
1   4       0
2   8       1
3  10       1

In [81]:
# Informacion que tenemos que mandar a campanas
import pandas as pd
# dataCampanas = pd.DataFrame(np.hstack((data_new['ID'].values.reshape(-1,1), y_campanas.reshape(-1,1))))
dataCampanas = pd.DataFrame(np.hstack((data_new['ID'].values.reshape(-1,1), y_campanas.reshape(-1,1))),columns=['ID','y_pred'])
dataCampanas.to_csv("DataCampanas.csv")

¡Y ya está! Lo básico de `scikit-learn` está aquí. Lo próximo será usar diferentes tipos de modelos y examinar con rigor su rendimiento para poder seleccionar el que mejor funcione para nuestros datos.

In [ ]:
# FIN!!